-- 023: Putaway fit exceptions (bin too small / too large) and override logging

CREATE TABLE IF NOT EXISTS public.putaway_exceptions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_code character varying(100) NOT NULL,
    rejected_location character varying(100),
    rejected_location_id integer,
    reason character varying(30) NOT NULL,
    requested_qty numeric(18,6),
    fits_qty numeric(18,6),
    override_location character varying(100),
    notes text,
    created_by integer,
    created_at timestamp with time zone DEFAULT now()
);

COMMENT ON TABLE public.putaway_exceptions IS
  'Worker reported bin too small/too large during putaway; used to skip that bin and optionally split qty';

ALTER TABLE public.putaway_logs
    ADD COLUMN IF NOT EXISTS exception_reason character varying(40);
ALTER TABLE public.putaway_logs
    ADD COLUMN IF NOT EXISTS is_override boolean DEFAULT false;

CREATE INDEX IF NOT EXISTS idx_putaway_exceptions_item
    ON public.putaway_exceptions (item_code, created_at DESC);
