-- 024: Max qty of an item that fits in a bin (no cube / LWH required)

ALTER TABLE public.items
    ADD COLUMN IF NOT EXISTS max_qty_per_bin numeric(18,6);

COMMENT ON COLUMN public.items.max_qty_per_bin IS
  'Default max units of this SKU that fit in one pick/storage bin. NULL = no item default.';

CREATE TABLE IF NOT EXISTS public.item_bin_capacities (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_code character varying(100) NOT NULL,
    location_id integer NOT NULL REFERENCES public.warehouse_locations(id),
    max_qty numeric(18,6) NOT NULL CHECK (max_qty > 0),
    updated_at timestamp with time zone DEFAULT now(),
    UNIQUE (item_code, location_id)
);

COMMENT ON TABLE public.item_bin_capacities IS
  'Override: this SKU fits at most max_qty in this specific bin. Learned from putaway fit exceptions or set in master.';

CREATE INDEX IF NOT EXISTS idx_item_bin_capacities_item
    ON public.item_bin_capacities (item_code);
