-- 032b: Putaway sessions for batch tote workflow
CREATE TABLE IF NOT EXISTS public.putaway_sessions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    warehouse_id integer NOT NULL,
    zone character varying(10),
    status character varying(20) DEFAULT 'picking' NOT NULL,
    started_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    completed_at timestamp with time zone
);

COMMENT ON TABLE public.putaway_sessions IS
  'Batch putaway session: worker picks items into tote, then distributes to storage.';

CREATE TABLE IF NOT EXISTS public.putaway_session_items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id integer NOT NULL REFERENCES public.putaway_sessions(id) ON DELETE CASCADE,
    item_code character varying(100) NOT NULL,
    source_location_id integer NOT NULL REFERENCES public.warehouse_locations(id),
    qty numeric(18,6) NOT NULL,
    status character varying(20) DEFAULT 'picked' NOT NULL,
    target_location_id integer REFERENCES public.warehouse_locations(id),
    putaway_log_id integer,
    created_at timestamp with time zone DEFAULT now()
);

COMMENT ON TABLE public.putaway_session_items IS
  'Items picked into tote during a putaway session, awaiting placement into storage.';

CREATE INDEX IF NOT EXISTS idx_psi_session
    ON public.putaway_session_items (session_id, status);

CREATE INDEX IF NOT EXISTS idx_ps_user
    ON public.putaway_sessions (user_id, status);

-- Function to cancel stale sessions (>2 hours)
CREATE OR REPLACE FUNCTION cancel_stale_putaway_sessions()
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
    UPDATE public.putaway_sessions
    SET status = 'cancelled', completed_at = now(), updated_at = now()
    WHERE status = 'picking'
      AND updated_at < now() - interval '2 hours';
END $$;
